### ISSUE TITLE
Stats on DIME code review

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ReplicableResearch#6]
- [x] Ask Dan how many paper went through WP peer review
- [x] Look at how many codes did not run at first

**Comment by luizaandrade** [comment]
- In the last 2 years, 16 Working Papers went through peer review, which includes code review (code review varies from simple push-button replication to a complete review of the analysis and construction files, depending on the material provided and on the time it takes to replicate the results)
- 3 of them could not be run on the first try
- 6 of them were resubmitted because part of the results could not be replicated
- 4 of them were resubmitted more than once

**Comment by luizaandrade** [comment]
@gbedoyaWB, the number for DIME WP review are above.

**Comment by gbedoyaWB** [comment]
@luizaandrade 
Thank you! These are great!

**Comment by luizaandrade** [comment]
As discussed in person, DIA toolkit was code reviewed as well.
